# This is a basic workflow to help you get started with Actions

name: smx-updater

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout-repo
        uses: actions/checkout@v2
      
      - name: dispatching
        uses: appleboy/scp-action@master
        with:
          host: s1.csgowiki.top
          username: csgo
          password: ${{ secrets.PASSWORD_S1 }}
          source: "plugins/csgowiki-pack.smx"
          target: "steamcmd/games/csgo/csgo/addons/sourcemode/logs/"
